## Part 2: Practical Challenge

Scenario: "The Bookshop Analyst"
You're a data analyst for an online bookshop. The operations team has exported their inventory to a CSV and they need your help making sense of it.

**Challenge 1: Build and Inspect the Dataset**

Create the following DataFrame and perform a health check:

Tasks:

1. Use .info() — how many non-null values does each column have?

2. Use .describe() — what's the average price and maximum units sold?

3. Add a revenue column: price × units_sold.

4. What is the total revenue across all books?

In [98]:
import pandas as pd

books = pd.DataFrame({
    'title': ['The Pragmatic Programmer', 'Clean Code', 'Python Crash Course',
              'Data Science from Scratch', 'Designing Data-Intensive Apps'],
    'author': ['Hunt & Thomas', 'Robert Martin', 'Eric Matthes',
               'Joel Grus', 'Martin Kleppmann'],
    'genre': ['Tech', 'Tech', 'Tech', 'Data', 'Data'],
    'price': [45.99, 38.50, 29.99, 42.00, 55.00],
    'units_sold': [121, 95, 200, 80, 60],
    'in_stock': [True, True, False, True, False]
})
display(books)

,title,author,genre,price,units_sold,in_stock
0,The Pragmatic Programmer,Hunt & Thomas,Tech,45.99,121,True
1,Clean Code,Robert Martin,Tech,38.50,95,True
2,Python Crash Course,Eric Matthes,Tech,29.99,200,False
3,Data Science from Scratch,Joel Grus,Data,42.00,80,True
4,Designing Data-Intensive Apps,Martin Kleppmann,Data,55.00,60,False

In [99]:
print(books.info())  # non-null value -> with acual data (null value -> missing data)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       5 non-null      object
 1   author      5 non-null      object
 2   genre       5 non-null      object
 3   price       5 non-null      float64
 4   units_sold  5 non-null      int64
 5   in_stock    5 non-null      bool
dtypes: bool(1), float64(1), int64(1), object(3)
memory usage: 333.0+ bytes
None

In [100]:
# summary statistics for numeric columns
display(books.describe())  

print(f"Average Price: £{books['price'].mean():,.2f}")
print(f"Max Unit Sold: {books['units_sold'].max()}")

           price  units_sold
count   5.000000    5.000000
mean   42.296000  111.200000
std     9.232715   54.403125
min    29.990000   60.000000
25%    38.500000   80.000000
50%    42.000000   95.000000
75%    45.990000  121.000000
max    55.000000  200.000000

Average Price: £42.30
Max Unit Sold: 200

In [101]:
# add revenue column to the DataFrame and calculate total revenue
books ['revenue'] = (books['price'] * books['units_sold']).astype(float)
display(books)

print(f"Total revenue: £{books['revenue'].sum():,.2f}") # ,.2f -> commas as thousands separators & 2 decimal

,title,author,genre,price,units_sold,in_stock,revenue
0,The Pragmatic Programmer,Hunt & Thomas,Tech,45.99,121,True,5564.79
1,Clean Code,Robert Martin,Tech,38.50,95,True,3657.50
2,Python Crash Course,Eric Matthes,Tech,29.99,200,False,5998.00
3,Data Science from Scratch,Joel Grus,Data,42.00,80,True,3360.00
4,Designing Data-Intensive Apps,Martin Kleppmann,Data,55.00,60,False,3300.00

Total revenue: £21,880.29

**Challenge 2: Indexing & Filtering**

Tasks:

1. Use .loc to select only title and revenue for Data genre books.

2. Use .iloc to retrieve the last 3 rows and first 3 columns.

3. Filter books that are in stock AND have a price above £40.

4. Find the book with the highest revenue using .loc with .idxmax().

In [102]:
# select title & revenue for 'Data' genre book
display(books[['title', 'revenue']].loc[books['genre'] == 'Data']) 

display(books.loc[books['genre'] == 'Data', ['title', 'revenue']])  # alternative way

                           title  revenue
3      Data Science from Scratch   3360.0
4  Designing Data-Intensive Apps   3300.0

                           title  revenue
3      Data Science from Scratch   3360.0
4  Designing Data-Intensive Apps   3300.0

In [103]:
# retrieve last 3 rows & first 3 columns
display(books.iloc[-3:, 0:3])

                           title            author genre
2            Python Crash Course      Eric Matthes  Tech
3      Data Science from Scratch         Joel Grus  Data
4  Designing Data-Intensive Apps  Martin Kleppmann  Data

In [104]:
# select books in stock with price > £40.00
display(books.loc[(books['in_stock'] == True) & (books['price'] > 40.00)])

,title,author,genre,price,units_sold,in_stock,revenue
0,The Pragmatic Programmer,Hunt & Thomas,Tech,45.99,121,True,5564.79
3,Data Science from Scratch,Joel Grus,Data,42.00,80,True,3360.00

In [105]:
# select book with the highest revenue
display(books.loc[books['revenue'].idxmax()])  # loc with idxmax() to get the row with the max revenue
print("\n")

top_book = books.loc[books['revenue'].idxmax()]
print(f"Top earner: {top_book['title']} — £{top_book['revenue']:,.2f}")

display(books.iloc[books['revenue'].argmax()]) # iloc with argmax() to get the row with the max revenue

display(books.sort_values('revenue').tail(1))  # sort by revenue and display the last (highest) row

display(books.nlargest(1, 'revenue'))   # display the row with the largest revenue value

title         Python Crash Course
author               Eric Matthes
genre                        Tech
price                       29.99
units_sold                    200
in_stock                    False
revenue                    5998.0
Name: 2, dtype: object

Top earner: Python Crash Course — £5,998.00

title         Python Crash Course
author               Eric Matthes
genre                        Tech
price                       29.99
units_sold                    200
in_stock                    False
revenue                    5998.0
Name: 2, dtype: object

,title,author,genre,price,units_sold,in_stock,revenue
2,Python Crash Course,Eric Matthes,Tech,29.99,200,False,5998.0

,title,author,genre,price,units_sold,in_stock,revenue
2,Python Crash Course,Eric Matthes,Tech,29.99,200,False,5998.0

**Challenge 3: Transform, Sort & Rank**

Tasks:

1. Use .apply() to add a price_tier column: 'Budget' (< £35), 'Standard' (£35–£50), 'Premium' (> £50).

2. Sort the DataFrame by revenue descending.

3. Add a sales_rank column using .rank(ascending=False).

4. Use .map() to encode genre as a number: {'Tech': 0, 'Data': 1}.

In [106]:
# add price tier
def price_tier(price):
    return 'Budget' if price < 35 else 'Premium' if price > 50 else 'Standard'

display(books.assign(price_tier=books['price'].apply(price_tier)))  # add price tier column using apply() 

books['price_tier'] = books['price'].apply(price_tier)
display(books)

,title,author,genre,price,units_sold,in_stock,revenue,price_tier
0,The Pragmatic Programmer,Hunt & Thomas,Tech,45.99,121,True,5564.79,Standard
1,Clean Code,Robert Martin,Tech,38.50,95,True,3657.50,Standard
2,Python Crash Course,Eric Matthes,Tech,29.99,200,False,5998.00,Budget
3,Data Science from Scratch,Joel Grus,Data,42.00,80,True,3360.00,Standard
4,Designing Data-Intensive Apps,Martin Kleppmann,Data,55.00,60,False,3300.00,Premium

,title,author,genre,price,units_sold,in_stock,revenue,price_tier
0,The Pragmatic Programmer,Hunt & Thomas,Tech,45.99,121,True,5564.79,Standard
1,Clean Code,Robert Martin,Tech,38.50,95,True,3657.50,Standard
2,Python Crash Course,Eric Matthes,Tech,29.99,200,False,5998.00,Budget
3,Data Science from Scratch,Joel Grus,Data,42.00,80,True,3360.00,Standard
4,Designing Data-Intensive Apps,Martin Kleppmann,Data,55.00,60,False,3300.00,Premium

In [107]:
# sort df by revenue in descending order
display(books.sort_values('revenue', ascending=False))

,title,author,genre,price,units_sold,in_stock,revenue,price_tier
2,Python Crash Course,Eric Matthes,Tech,29.99,200,False,5998.00,Budget
0,The Pragmatic Programmer,Hunt & Thomas,Tech,45.99,121,True,5564.79,Standard
1,Clean Code,Robert Martin,Tech,38.50,95,True,3657.50,Standard
3,Data Science from Scratch,Joel Grus,Data,42.00,80,True,3360.00,Standard
4,Designing Data-Intensive Apps,Martin Kleppmann,Data,55.00,60,False,3300.00,Premium

In [108]:
# add sales rank column
books['sales_rank'] = books['units_sold'].rank(ascending=False).astype(int)
display(books)

,title,author,genre,price,units_sold,in_stock,revenue,price_tier,sales_rank
0,The Pragmatic Programmer,Hunt & Thomas,Tech,45.99,121,True,5564.79,Standard,2
1,Clean Code,Robert Martin,Tech,38.50,95,True,3657.50,Standard,3
2,Python Crash Course,Eric Matthes,Tech,29.99,200,False,5998.00,Budget,1
3,Data Science from Scratch,Joel Grus,Data,42.00,80,True,3360.00,Standard,4
4,Designing Data-Intensive Apps,Martin Kleppmann,Data,55.00,60,False,3300.00,Premium,5

In [109]:
# encode genre column to numeric values
books['genre_encoded'] = books['genre'].map({'Tech': 0, 'Data': 1})
display(books)

,title,author,genre,price,units_sold,in_stock,revenue,price_tier,sales_rank,genre_encoded
0,The Pragmatic Programmer,Hunt & Thomas,Tech,45.99,121,True,5564.79,Standard,2,0
1,Clean Code,Robert Martin,Tech,38.50,95,True,3657.50,Standard,3,0
2,Python Crash Course,Eric Matthes,Tech,29.99,200,False,5998.00,Budget,1,0
3,Data Science from Scratch,Joel Grus,Data,42.00,80,True,3360.00,Standard,4,1
4,Designing Data-Intensive Apps,Martin Kleppmann,Data,55.00,60,False,3300.00,Premium,5,1

🏆 **Stretch Challenge (Optional)**

The manager wants a report comparing average price and total revenue by price_tier. Use groupby() to generate this summary. Which tier contributes the most total revenue despite having the lowest average price?