In [1]:
import pandas as pd
import numpy as np

print(f"Pandas version: {pd.__version__}")
print("✅ Environment is ready!")

Pandas version: 1.5.3
✅ Environment is ready!

In [3]:
import pandas as pd
# A simple list of data
data = [10, 20, 30, 40]
# Converting it to a Pandas Series
s = pd.Series(data, index=['a', 'b', 'c', 'd'])
print(s)

a    10
b    20
c    30
d    40
dtype: int64

In [3]:
# A dictionary where keys are column names
data = {
    'Apples': [3, 2, 0, 1],
    'Oranges': [0, 3, 7, 2]
}
df = pd.DataFrame(data)
print(df)

   Apples  Oranges
0       3        0
1       2        3
2       0        7
3       1        2

In [5]:
data = {
    "state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
    "year": [2000, 2001, 2002, 2001, 2002, 2003],
    "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]
}

frame = pd.DataFrame(data)  
frame.tail(2)

    state  year  pop
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [6]:
data = {
    "state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
    "year": [2000, 2001, 2002, 2001, 2002, 2003],
    "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]
}

Year = pd.DataFrame(data)  
Year.tail(2)

    state  year  pop
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [ ]:
import pandas as pd
import numpy as np
# [DEMO] Detecting missing values
# np.nan = "Not a Number", pandas/numpy's way of marking missing/empty data.
data_with_nan = pd.Series([1, np.nan, 3.5, np.nan, 7])

print("Original data:")
display(data_with_nan)

print("\nWhich values are missing?")
display(data_with_nan.isna())  # isna() → True where value is NaN

print("\nWhich values are NOT missing?")
display(data_with_nan.notna())  # notna() → opposite of isna()

data_filled_zero = data_with_nan.fillna(0) # replace with 0

print("Filled with 0:")
display(data_filled_zero)

Original data:

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

Which values are missing?

0    False
1     True
2    False
3     True
4    False
dtype: bool

Which values are NOT missing?

0     True
1    False
2     True
3    False
4     True
dtype: bool

Filled with 0:

0    1.0
1    0.0
2    3.5
3    0.0
4    7.0
dtype: float64

In [15]:
Inventory = pd.DataFrame(fruit_data, index=["Apple", "Banana", "Cherry", "Date"], columns=["quantity"])
Inventory

        quantity
Apple        100
Banana        40
Cherry       200
Date          20

In [17]:
fruit_data = {
    "fruit": ["Apple", "Banana", "Cherry", "Date"],
    "quantity": [100, 40, 200, 20]
}
Inventory = pd.DataFrame(fruit_data)
Inventory

    fruit  quantity
0   Apple       100
1  Banana        40
2  Cherry       200
3    Date        20

In [20]:
marks = pd.DataFrame({
    "Student": ["Alice", "Bob", "Charlie", "David"],
    "Math": [85, 45, 92, 60],
    "Science": [70, 85, 88, 72]
})

def check_status(marks):
    if marks >= 60:      # if/else: run one branch or other, based on condition
        return "Pass"
    else:
        return "Fail"

# .apply(check_status) run function on every value in 'Math' column, one by one.
marks['Status'] = marks['Math'].apply(check_status)

marks

   Student  Math  Science Status
0    Alice    85       70   Pass
1      Bob    45       85   Fail
2  Charlie    92       88   Pass
3    David    60       72   Pass

In [10]:
data = {
    "state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
    "year": [2000, 2001, 2002, 2001, 2002, 2003],
    "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]
}

frame = pd.DataFrame(data)  # turn dictionary into table
display(frame)

display(frame['pop']) # display the 'pop' column

display(frame[['year', 'pop']]) # display the 'year' and 'pop' columns

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

0    1.5
1    1.7
2    3.6
3    2.4
4    2.9
5    3.2
Name: pop, dtype: float64

   year  pop
0  2000  1.5
1  2001  1.7
2  2002  3.6
3  2001  2.4
4  2002  2.9
5  2003  3.2

In [16]:
# [DEMO] Detecting missing values
# np.nan = "Not a Number", pandas/numpy's way of marking missing/empty data.
data_with_nan = pd.Series([1, np.nan, 3.5, np.nan, 7])

print("Original data:")
display(data_with_nan)

print("\nWhich values are missing?")
display(data_with_nan.isna()) # isna() → True where value is NaN

print("\nHow many missing values?")
display(data_with_nan.isna().sum())  # isna() → True where value is NaN

Original data:

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

Which values are missing?

0    False
1     True
2    False
3     True
4    False
dtype: bool

How many missing values?

2

In [29]:
def add_calculator(a, b):
    return a - b

result = add_calculator(5, 3)
print(result)

2

In [1]:
def calculator(number):
    answer = number * 2
    return answer

answer = calculator(5)
answer

10